### ISSUE TITLE
微信小程序绑定Key报错

### ISSUE THREAD

**Issue by chanlk** [wahao/Bark-MP-helper#2]
在推送管理->绑定bark的时候会报错, "文本存在违法违规内容,平台拦截推送";
绑定邮箱的时候也是如此;

**Comment by wahao** [comment]
不会啊       可以加我微信看看 haoye42

**Comment by wahao** [comment]
> 在推送管理->绑定bark的时候会报错, "文本存在违法违规内容,平台拦截推送";
> 绑定邮箱的时候也是如此;

不会啊 可以加我微信看看 haoye42

**Comment by HellyW** [comment]
@chanlk    平台所发送信息都通过腾讯安全文本过滤，之前是腾讯平台误报。已解决。  可再次尝试绑定
